# ─── Cấu hình Dataset ─────────────────────────────────────────────────────────
dataset:
  root: dataset/raw/yolo_helmet_dataset
  yaml: dataset/dataset.yaml

# ─── Cấu hình Model ───────────────────────────────────────────────────────────
model:
  name: yolov8n.pt  # yolov8n / yolov8s / yolov8m / yolov8l / yolov8x

# ─── WebDataset Sharding ──────────────────────────────────────────────────────
sharding:
  output_dir: dataset/shards   # Thư mục chứa các file .tar shards
  shard_size: 1000             # Số ảnh mỗi shard
  extract_limit: 1             # Số shard tối đa cần giải nén mỗi split (set 0 hoặc bỏ trống để giải nén tất cả)

# ─── Hyperparameters huấn luyện ───────────────────────────────────────────────
train:
  epochs: 1
  imgsz: 640
  batch: 64
  patience: 4
  device: [4, 5]
  project: Helmet_Detection_Project
  name: yolov8_binary_class

# ─── MLflow Tracking ──────────────────────────────────────────────────────────
mlflow:
  tracking_uri: http://localhost:5001
