artifact_location: /mmlab_students/storageStudents/nguyenvd/uit_medseg/CS317_MLOps/runs/mlflow/355964063655827409
creation_time: 1778121876366
experiment_id: '355964063655827409'
last_update_time: 1778121876366
lifecycle_stage: active
name: Helmet_Detection_Project
