app:
  name: uit-medseg-vision
  env: development
  log_level: INFO
  gpu_id: 0

storage:
  logs_dir: storage/logs

events:
  backend: file
  output_file: storage/logs/events.jsonl

streams:
  # scan_camera_dir: /workspace/apps/vision_service/configs/camera
  scan_camera_dir: camera

pipeline:
  streammux_width: 960
  streammux_height: 544
  batched_push_timeout_usec: 40000
  max_sources: 1
  sink: rtmp
  frame_log_interval_sec: 5.0

infer:
  enabled: true
  config_file: /workspace/apps/vision_service/configs/infer/pgie_yolov8_helmet.txt
  unique_id: 1
  summary_interval_sec: 5.0
  emit_frame_events: false

visualization:
  enabled: true
  display_text: true
  display_bbox: true
  display_clock: false
  osd_process_mode: 0

rtsp:
  enabled: false
  host: "127.0.0.1"
  udp_port: 5400
  rtsp_port: 8554
  mount_point: "/vision"
  codec: "h264"
  bitrate: 2500000
  iframe_interval: 15
  payload_type: 96
  rtp_mtu: 1400
  udp_buffer_size: 2097152
  sps_pps_interval: -1
  rtsp_repay_enabled: true
  rtsp_repay_jitter_latency_ms: 0
  rtsp_repay_jitter_drop_on_latency: true
  rtsp_repay_leaky_queue_enabled: true
  rtsp_transport: "tcp"
  udpsink_sync: true
  udpsink_async: false
  udpsink_qos: false
  debug_h264_output_file: ""

rtmp:
  enabled: true
  # MediaMTX publish URL format: rtmp://<host>/<path>
  location: "rtmp://192.168.20.154:1935/vision1 live=1"
  sink_sync: true
  sink_async: false
  streamable_mux: true

tracker:
  enabled: true
  gpu_id: 0
  tracker_width: 640
  tracker_height: 640
  ll_lib_file: /opt/nvidia/deepstream/deepstream-6.4/lib/libnvds_nvmultiobjecttracker.so
  ll_config_file: /opt/nvidia/deepstream/deepstream-6.4/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
  display_tracking_id: false
