artifact_location: /mmlab_students/storageStudents/nguyenvd/uit_medseg/CS317_MLOps/runs/mlflow/0
creation_time: 1778121876287
experiment_id: '0'
last_update_time: 1778121876287
lifecycle_stage: active
name: Default
